### ISSUE TITLE
Generate Unique IDs in Canvas outcomes csv

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/checkit#11]
Ran into an interesting error with the Outcomes CSV. For some reason, I could not get some of my outcomes to upload -- it kept throwing an error. Turns out the error message gets emailed to you:

`Hello Lewis, Dr. Drew  M.,

Your outcomes were successfully imported, but with the following issues (up to the first 100 warnings):

Row 2: Outcome with ID tbil-la_00_E1 already exists in another unrelated course or account (MA-238-101: Differential Equations I)
Row 3: Outcome with ID tbil-la_01_E2 already exists in another unrelated course or account (MA-238-101: Differential Equations I)
Row 4: Outcome with ID tbil-la_02_E3 already exists in another unrelated course or account (MA-238-101: Differential Equations I)
Row 5: Outcome with ID tbil-la_03_V1 already exists in another unrelated course or account (MA-238-101: Differential Equations I)

You can now manage them at https://usaonline.southalabama.edu/courses/7134/outcomes

Thank you,
Instructure`

In particular, MA-238-101 is @StevenClontz 's course, and he presumably had these outcomes as testing the implementation of the Canvas Outcomes CSV. It seems that we need to generate *unique* IDs, or two instructors at the same institution may run into trouble.

Workaround: I created different IDs by hand for my course.

**Comment by StevenClontz** [comment]
That's unexpected. Yeah, I'll change the IDs to `{courseslug}_{int}_{objectiveslug}_{randominteger}` which should fix this (with 1 in a million odds of failure).
