### ISSUE TITLE
Matrix generator

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/checkit#17]
See https://github.com/TeamBasedInquiryLearning/checkit-tbil-la/issues/7

Given dimensions and number of pivots, generate random matrix where:

- uses integers between -9 and 9 for itself and its RREF
- doesn't have repeated columns
- doesn't have a column of zeros

**Comment by siwelwerd** [comment]
Some of the RREFs that are supposed to be nice (i.e. integers) are not, I'll drop an example here the next time I come across one as well.

**Comment by StevenClontz** [comment]
Thinking about implementation, I'll probably generate the RREF using numbers between -3 and 3 for non-pivot columns. Then I'll generate random pivot columns for the original using numbers between -5 and 5. Then the non-pivots are determined by the RREF. That gets non-pivot values between -15 and 15, which I think is acceptable.

**Comment by StevenClontz** [comment]
Well the non-pivots could be worse actually (3*5+3*5+...). But I think those edge cases are still acceptable... we'll see how it works in practice once I hack this up.

**Comment by StevenClontz** [comment]
Closed in 05517b5
