### ISSUE TITLE
LE1 vocabulary mismatch

### ISSUE THREAD

**Issue by jbolkema** [StevenClontz/checkit#75]
Some of the LE1 problems display a vector equation but refer to it as an augmented matrix in Task 1. (Task 2 is correct.)
![Screen Shot 2022-10-07 at 10 50 55 AM](https://user-images.githubusercontent.com/106885324/194619924-447259ef-f47c-4b80-b565-9f18a313d118.png)

**Comment by StevenClontz** [comment]
moving this to https://github.com/TeamBasedInquiryLearning/linear-algebra/issues
